#spring.webflux.base-path=dairyapp
server.compression.enabled=true
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

#springdoc.api-docs.groups.enabled=true
#springdoc.swagger-ui.path=/swagger-doc/swagger-ui.html
#springdoc.api-docs.path=/swagger-doc/v3/api-docs


spring.mail.host=mail.emtechhouse.co.ke
spring.mail.port=587
spring.mail.username=no-reply@emtechhouse.co.ke
spring.mail.password={Pass123$$}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.starttls.enable=true

mm.email.sender = no-reply@emtechhouse.co.ke
mm.email.host = mail.emtechhouse.co.ke
mm.email.port = 587
mm.email.password = Pass123$$
mm.email.subject = YOUR LOGIN CREDENTIALS
mm.email.greetings = <b>Dear User,</b><br/>
mm.email.signoff = <br/><br/><b>Kindly change the credentials especially password after your first sign in.</b>
mm.email.body1 = Your login credentials are : <br/> <b>Username   :   <b>
mm.email.body2 = <br/><b>Password   :   </b>
mm.email.body3 = Your <b>Password Reset Token </b> is : <h1>   
mm.email.body4 = </h1><br/>Click <a href="
mm.email.body5 = "><b>
mm.email.body6 = </b></a>  to reset your Password.
mm.email.subject1 = PASSWORD RESET.

company_logo_path=/home/shivachi/prod/EMT_Dairy_App/resources/dairy_logo.jpg
equity_banner_path=/home/shivachi/prod/EMT_Dairy_App/resources/dairy_banner.jpg

jwt.secret=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
jwt.jwtExpirationMs=86400000

jwt.password.encoder.secret=mysecret
jwt.password.encoder.iteration=33
jwt.password.encoder.keylength=256

jwt.password.token.expirationMs=86400000
