server:
  error:
    include-message: always
  port: 9400
#  ssl:
#    key-store: /var/www/bahatife/uat/certs/bahati.jks
#    key-store-password: Emtech@25
#    key-store-type: JKS
#    key-password: Emtech@25
#    enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bahati_local
    username: opany
    password: Hillary2020@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: Africa/Nairobi
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  banner:
    location: classpath:static/banner.txt
  servlet:
    multipart:
      enabled: true
      max-file-size:  10MB
      max-request-size: 10MB
tilil:
    sendsms:
      url: https://api.tililtech.com/sms/v3/sendsms
    userId: BAHATIAGRO

dairy:
  company_logo_path: /home/ubuntu/prod/bahati/resources/dairy_logo.jpg
  report-path: /home/ubuntu/prod/bahati/resources/reports
  private-key: classpath:keys/private_key.pem
  lactovate-secret: secret123456
  quality-test-url: https://devcub.com/lactovate
#  company_logo_path: C:\\Users\\michael\\Documents\\springboot projects\\DAIRY_APP_BE\\src\\main\\resources\\dairy_logo.jpg
#  report-path: C:\\Users\\michael\\Documents\\springboot projects\\DAIRY_APP_BE\\src\\main\\resources\\reports


pagination:
  pageSize: 10

google:
  location:
    API-KEY: AIzaSyCtDO1QdXGeEnX5LA1qOQlpuChPkZJJb1I

ebs:
  url: https://sms.crossgatesolutions.com:18095/v1/bulksms/messages
  callbackurl:
    one: https://bahatidairy.emtechhouse.co.ke:9400/api/v1/sms-notifications/callback
  messagetype: promotional
  apiKey : AJKSF28ldksjshkjjlsjadkljhajkjshajskdhsjdkajasdkjh
#  apiKey : NDU4MThmODAxMzM2ODk3MUlELTQ2MmU4Y2QwZDA4YjQxOGU5ZjZjMTQ0ZGM0MmE4NDY5
  #ebs.apiKey = ZmMyYWRkYjEyMTkxY2Y4ZklELWZkODFhMGM3YjA1NjQwNGFhMDc1OGNiZmQ1MTA1MTVi
  profileCode: 2208021
##ebs.profileCode = 2211301


sms:
  enable: true





