server:
  error:
    include-message: always
  port: 9600

spring:
  datasource:
    url: jdbc:mariadb://52.15.152.26:3306/dairy
    username: emtech
    password: emtech@2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MariaDB53Dialect
        format_sql: true
    hibernate:

      ddl-auto: update
    show-sql: false


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: classpath:static/banner.txt

dairy:
  company_logo_path: /home/ubuntu/prod/EMT_012_DairyApp/resources/dairy_logo.jpg
  report-path: /home/ubuntu/prod/EMT_012_DairyApp/resources/reports
#  company_logo_path: /home/ibrahim/Downloads/dairy_logo.jpg
#  report-path: /home/ibrahim/JaspersoftWorkspace/MyReports


pagination:
  pageSize: 10




